name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7  # koristi MySQL sliku verzije 5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword  # Root password
          MYSQL_DATABASE: party_up  # Baza podataka koju ćeš koristiti
          MYSQL_USER: ${{ secrets.DB_USERNAME }}  # Korisničko ime za bazu (GitHub Secret)
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Lozinka za bazu (GitHub Secret)
        ports:
          - 3306:3306  # Port za MySQL
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up MySQL environment variables
        run: |
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/party_up" >> party-up-service/src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> party-up-service/src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> party-up-service/src/main/resources/application.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> party-up-service/src/main/resources/application.properties

      - name: Build with Maven
        run: |
          cd party-up-service
          mvn clean install

      - name: Run PMD Analysis
        run: |
          cd party-up-service
          mvn pmd:check

      - name: Run Tests with JaCoCo
        run: |
          cd party-up-service
          mvn test jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco
